name: .NET Single CS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Create temporary console project
        run: dotnet new console -n TempApp --force

      - name: Copy C# files into project
        run: cp *.cs TempApp/

      - name: Build project
        run: dotnet build TempApp --configuration Release

      - name: Run project
        run: dotnet run --project TempApp --configuration Release
